"""Research-only datasets, target labels, experiment records, and reports.

Sprint 4A exposes a local-only dataset loader that aligns bars + computed features.
Sprint 4B adds multi-symbol loading, an as_of lookahead guard, and a lightweight
research dataset manifest.
Phase 4A Target / Label Foundation adds audited forward-return labels in a separate
module. Labels are future outcomes only: never features, alpha, signals, or weights.
Sprint 5A adds an append-only experiment registry (discipline scaffolding for future
backtests; records metadata only, no backtest runs yet).
No trading, no model training, no Alpaca API calls.
"""

from alpaca_quant.research.data_contract import (
    ADJ_BACK_ADJUSTED,
    ADJ_NOT_APPLICABLE,
    ADJ_PIT_SAFE,
    ADJ_UNKNOWN,
    AVAILABILITY_LAGGED,
    AVAILABILITY_POINT_IN_TIME,
    DataContractError,
    FeatureSpec,
    assert_features_acceptable,
    classify_feature_specs,
    feature_availability_summary,
    normalize_feature_specs,
)
from alpaca_quant.research.dataset import (
    ResearchDatasetError,
    ResearchDatasetManifest,
    ResearchDatasetSummary,
    build_research_dataset_manifest,
    load_research_dataset,
    summarize_research_dataset,
)
from alpaca_quant.research.dataset_manifest import (
    DatasetManifest,
    DatasetManifestError,
    build_dataset_manifest,
    fingerprint_dataset,
    render_dataset_manifest_markdown,
)
from alpaca_quant.research.dataset_report import (
    DatasetReportConfig,
    DatasetReportError,
    attach_feature_set_id,
    build_dataset_inspection_report,
    render_dataset_inspection_markdown,
)
from alpaca_quant.research.experiment_registry import (
    ExperimentRecord,
    ExperimentRegistryError,
    append_experiment_record,
    capture_git_sha,
    create_experiment_run_id,
    new_experiment_record,
    read_experiment_records,
)
from alpaca_quant.research.experiment_runner import (
    ExperimentRunError,
    ExperimentRunResult,
    compute_config_hash,
    flatten_experiment_metrics,
    run_backtest_experiment,
)
from alpaca_quant.research.feature_registry import (
    FeatureDefinition,
    FeatureRegistry,
    FeatureRegistryError,
    FeatureSetValidation,
    RegistryValidationConfig,
    build_registry,
    compute_feature_set_id,
    export_feature_definitions,
    list_definitions,
    validate_definition,
    validate_feature_set,
)
from alpaca_quant.research.lineage_registry import (
    LINEAGE_RECORD_TYPE,
    LINEAGE_REGISTRY_SCHEMA_VERSION,
    LineageRecord,
    LineageRegistryError,
    append_lineage_record,
    build_lineage_record,
    entry_id_from_fingerprint,
    export_lineage_records,
    fingerprint_lineage_entry,
    lineage_record_from_manifest_report,
    query_lineage_records,
    read_lineage_records,
)
from alpaca_quant.research.ml_dataset import (
    AssembledMLDataset,
    DatasetConfig,
    MLDatasetError,
    assemble_ml_dataset,
)
from alpaca_quant.research.pit_joins import (
    PitJoinError,
    annotate_universe_membership,
    asof_join_reference,
    asof_join_summary,
    resolve_permanent_ids,
)
from alpaca_quant.research.splits import (
    SplitDefinitionError,
    TemporalSplit,
    assert_split_disjoint_and_purged,
    make_temporal_split,
    split_definitions_for_manifest,
    split_summary,
)
from alpaca_quant.research.target_report import (
    BOUNDARY_NOTE,
    TargetDefinition,
    TargetReportConfig,
    TargetReportError,
    build_target_qa_report,
    render_target_qa_markdown,
)
from alpaca_quant.research.targets import (
    TargetLabelError,
    TargetLabelSummary,
    TargetManifest,
    build_forward_return_labels,
    build_target_manifest,
    fingerprint_target_labels,
    summarize_target_labels,
)

__all__ = [
    "ADJ_BACK_ADJUSTED",
    "ADJ_NOT_APPLICABLE",
    "ADJ_PIT_SAFE",
    "ADJ_UNKNOWN",
    "AVAILABILITY_LAGGED",
    "AVAILABILITY_POINT_IN_TIME",
    "AssembledMLDataset",
    "DataContractError",
    "DatasetConfig",
    "DatasetManifest",
    "DatasetManifestError",
    "DatasetReportConfig",
    "DatasetReportError",
    "FeatureDefinition",
    "FeatureRegistry",
    "FeatureRegistryError",
    "FeatureSetValidation",
    "FeatureSpec",
    "LINEAGE_RECORD_TYPE",
    "LINEAGE_REGISTRY_SCHEMA_VERSION",
    "LineageRecord",
    "LineageRegistryError",
    "MLDatasetError",
    "RegistryValidationConfig",
    "attach_feature_set_id",
    "build_dataset_inspection_report",
    "build_registry",
    "compute_feature_set_id",
    "export_feature_definitions",
    "list_definitions",
    "render_dataset_inspection_markdown",
    "validate_definition",
    "validate_feature_set",
    "PitJoinError",
    "SplitDefinitionError",
    "TemporalSplit",
    "annotate_universe_membership",
    "asof_join_reference",
    "asof_join_summary",
    "assemble_ml_dataset",
    "assert_features_acceptable",
    "assert_split_disjoint_and_purged",
    "build_dataset_manifest",
    "build_lineage_record",
    "classify_feature_specs",
    "entry_id_from_fingerprint",
    "export_lineage_records",
    "feature_availability_summary",
    "fingerprint_lineage_entry",
    "fingerprint_dataset",
    "lineage_record_from_manifest_report",
    "make_temporal_split",
    "normalize_feature_specs",
    "render_dataset_manifest_markdown",
    "resolve_permanent_ids",
    "split_definitions_for_manifest",
    "split_summary",
    "ExperimentRecord",
    "ExperimentRegistryError",
    "ExperimentRunError",
    "ExperimentRunResult",
    "ResearchDatasetError",
    "ResearchDatasetManifest",
    "ResearchDatasetSummary",
    "BOUNDARY_NOTE",
    "TargetDefinition",
    "TargetLabelError",
    "TargetLabelSummary",
    "TargetManifest",
    "TargetReportConfig",
    "TargetReportError",
    "append_experiment_record",
    "append_lineage_record",
    "build_forward_return_labels",
    "build_research_dataset_manifest",
    "build_target_qa_report",
    "build_target_manifest",
    "capture_git_sha",
    "compute_config_hash",
    "create_experiment_run_id",
    "flatten_experiment_metrics",
    "fingerprint_target_labels",
    "load_research_dataset",
    "new_experiment_record",
    "query_lineage_records",
    "read_experiment_records",
    "read_lineage_records",
    "render_target_qa_markdown",
    "run_backtest_experiment",
    "summarize_research_dataset",
    "summarize_target_labels",
]
